import type { Metadata } from "next";
import { Inter } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-inter",
});

const giloryBold = localFont({
  src: "./fonts/Gilroy-Bold.ttf",
  style: "normal",
  variable: "--font-giloryBold",
});

const giloryMedium = localFont({
  src: "./fonts/Gilroy-Medium.ttf",
  style: "normal",
  variable: "--font-giloryMedium",
});

const gilorySemibold = localFont({
  src: "./fonts/Gilroy-Semibold.ttf",
  style: "normal",
  variable: "--font-gilorySemibold",
});

export const metadata: Metadata = {
  title: "OOR3D",
  description: "Generated by create next app",
  icons: {
    icon: "/images/favicon.ico",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${giloryBold.variable} ${giloryMedium.variable} ${gilorySemibold.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
